// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");

var WeekdayEra = {};

var YearDay = {};

var Style = {};

var Month = {};

function make(weekdayOpt, monthOpt, yearOpt, dayOpt, eraOpt, dateStyleOpt, timeStyleOpt, param) {
  var weekday = weekdayOpt !== undefined ? Caml_option.valFromOption(weekdayOpt) : undefined;
  var month = monthOpt !== undefined ? Caml_option.valFromOption(monthOpt) : undefined;
  var year = yearOpt !== undefined ? Caml_option.valFromOption(yearOpt) : undefined;
  var day = dayOpt !== undefined ? Caml_option.valFromOption(dayOpt) : undefined;
  var era = eraOpt !== undefined ? Caml_option.valFromOption(eraOpt) : undefined;
  var dateStyle = dateStyleOpt !== undefined ? Caml_option.valFromOption(dateStyleOpt) : undefined;
  var timeStyle = timeStyleOpt !== undefined ? Caml_option.valFromOption(timeStyleOpt) : undefined;
  return {
          weekday: weekday,
          era: era,
          year: year,
          day: day,
          month: month,
          dateStyle: dateStyle,
          timeStyle: timeStyle
        };
}

var Options = {
  make: make
};

function make$1(dateOpt, localeOpt, options, param) {
  var date = dateOpt !== undefined ? Caml_option.valFromOption(dateOpt) : new Date();
  var locale = localeOpt !== undefined ? Caml_option.valFromOption(localeOpt) : undefined;
  return new (Intl.DateTimeFormat)(locale, options).format(date);
}

function makeFromString(dateOpt, localeOpt, options, param) {
  var date = dateOpt !== undefined ? dateOpt : new Date().toISOString();
  var locale = localeOpt !== undefined ? Caml_option.valFromOption(localeOpt) : undefined;
  return new (Intl.DateTimeFormat)(locale, options).format(new Date(date));
}

exports.WeekdayEra = WeekdayEra;
exports.YearDay = YearDay;
exports.Style = Style;
exports.Month = Month;
exports.Options = Options;
exports.make = make$1;
exports.makeFromString = makeFromString;
/* No side effect */
