// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");

var Type = {};

var Style = {};

function make(styleOpt, type_Opt, param) {
  var style = styleOpt !== undefined ? Caml_option.valFromOption(styleOpt) : undefined;
  var type_ = type_Opt !== undefined ? Caml_option.valFromOption(type_Opt) : undefined;
  return {
          type: type_,
          style: style
        };
}

var Options = {
  make: make
};

function make$1(listData, localeOpt, options, param) {
  var locale = localeOpt !== undefined ? Caml_option.valFromOption(localeOpt) : undefined;
  var options$1;
  if (options !== undefined) {
    var style = options.style;
    var type_ = options.type;
    options$1 = type_ !== undefined && (type_ === "disjunction" || type_ === "conjunction") && style !== undefined && (style === "narrow" || style === "short") ? ({
          type: "unit",
          style: style
        }) : options;
  } else {
    options$1 = undefined;
  }
  return new (Intl.ListFormat)(locale, options$1).format(listData);
}

exports.Type = Type;
exports.Style = Style;
exports.Options = Options;
exports.make = make$1;
/* No side effect */
