// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");

var Style = {};

function make(value, localeOpt, minimumFractionDigitsOpt, maximumFractionDigitsOpt, currencyOpt, param) {
  var locale = localeOpt !== undefined ? Caml_option.valFromOption(localeOpt) : undefined;
  var minimumFractionDigits = minimumFractionDigitsOpt !== undefined ? Caml_option.valFromOption(minimumFractionDigitsOpt) : 2;
  var maximumFractionDigits = maximumFractionDigitsOpt !== undefined ? Caml_option.valFromOption(maximumFractionDigitsOpt) : 2;
  var currency = currencyOpt !== undefined ? Caml_option.valFromOption(currencyOpt) : undefined;
  return new (Intl.NumberFormat)(locale, {
                minimumFractionDigits: minimumFractionDigits,
                maximumFractionDigits: maximumFractionDigits,
                style: "currency",
                currency: currency
              }).format(value);
}

var Currency = {
  make: make
};

function make$1(value, localeOpt, minimumFractionDigitsOpt, maximumFractionDigitsOpt, param) {
  var locale = localeOpt !== undefined ? Caml_option.valFromOption(localeOpt) : undefined;
  var minimumFractionDigits = minimumFractionDigitsOpt !== undefined ? Caml_option.valFromOption(minimumFractionDigitsOpt) : 2;
  var maximumFractionDigits = maximumFractionDigitsOpt !== undefined ? Caml_option.valFromOption(maximumFractionDigitsOpt) : 2;
  return new (Intl.NumberFormat)(locale, {
                minimumFractionDigits: minimumFractionDigits,
                maximumFractionDigits: maximumFractionDigits,
                style: "decimal",
                currency: undefined
              }).format(value);
}

var Decimal = {
  make: make$1
};

function make$2(value, localeOpt, minimumFractionDigitsOpt, maximumFractionDigitsOpt, param) {
  var locale = localeOpt !== undefined ? Caml_option.valFromOption(localeOpt) : undefined;
  var minimumFractionDigits = minimumFractionDigitsOpt !== undefined ? Caml_option.valFromOption(minimumFractionDigitsOpt) : 0;
  var maximumFractionDigits = maximumFractionDigitsOpt !== undefined ? Caml_option.valFromOption(maximumFractionDigitsOpt) : 0;
  return new (Intl.NumberFormat)(locale, {
                minimumFractionDigits: minimumFractionDigits,
                maximumFractionDigits: maximumFractionDigits,
                style: "percent",
                currency: undefined
              }).format(value);
}

var Percent = {
  make: make$2
};

exports.Style = Style;
exports.Currency = Currency;
exports.Decimal = Decimal;
exports.Percent = Percent;
/* No side effect */
