name: Run tests on PR

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test
        env:
          TZ: "Europe/Stockholm"
